### PR TITLE
Add snippet persistence for an auto-yasnippet

### PR DESCRIPTION
**Pull request by jasonm23**
Also reformatted README (also added notes on auto snippet persistence)

### CODE REVIEW

**Comment by abo-abo** [comment]
Thanks! I had to gut your code slightly to make it more stylish.
You can review the changes and ask me questions if there are any.

**Comment by jasonm23** [comment]
Did you start a new branch/pr to make the changes?

**Comment by jasonm23** [comment]
I specifically wrote feature to avoid an unwanted buffer.  It's trivial to have it persist and be loaded automatically, ie. thru a wrapper function. eg. `aya-persist-and-activate`.

I'd much rather be given feedback on how you want it to work and make that happen for you while retaining the functionality as I wrote it.

**Comment by jasonm23** [comment]
Similarly editing an existing snippet (or the newly created one) would be better done by a different feature.

The purpose of this is to stay out of the way and let you get on with the next snippet with minimal interruption.

**Comment by abo-abo** [comment]
> Similarly editing an existing snippet (or the newly created one) would be better done by a different feature.
> 
> The purpose of this is to stay out of the way and let you get on with the next snippet with minimal interruption.

I like this approach. Yasnippet's <kbd>C-c C-c</kbd> will load the snippet and kill the buffer.

There's too much magic in your approach, it's not apparent what has been done.
Doing it my way, nothing is done until user does <kbd>C-x C-s C-c C-c</kbd>.

**Comment by abo-abo** [comment]
You can customize `aya-insert-snippet-function` as you like.
If you want, I'll merge modifications to `aya-insert-snippet-function-extra`.
`aya-insert-snippet-function-default` will remain the default behavior.

**Comment by jasonm23** [comment]
Sounds like a plan.

**Comment by jasonm23** [comment]
I've had a think and I feel that these to methods of yasnippet creation are both valid, and useful within the same workflow.

For myself, often I will just want to create the new yasnippet without interruption, and on occasion I'd need to make some edits.

As such, having to re-configure the function used for a single command, totally derails such a workflow.  Obviously what we want in a package is reduction of tedium and disruption, so I've made these features separate commands.

I'll create a new PR shortly.

**Pull request closed without merging**
